# Generated by Django 5.1.15 on 2026-09-16 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='practiced_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
